### ISSUE TITLE
Implicit function (compile on Ubuntu 12.04 LTE)

### ISSUE THREAD

**Issue by tmnkey** [scality/RestBlockDriver#30]
Probably depending on version of kernel header, some function were not visible from the dewblock source codes. I just hardcoded to compile. Now I am configuring to see how it goes. 

Linux app05 3.2.0-61-generic #92-Ubuntu SMP Mon Mar 31 23:47:59 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

1) Got this

/nfs/test/packages/RestBlockDriver
root@app05:/nfs/test/packages/RestBlockDriver# make
make -C /lib/modules/3.2.0-61-generic/build M=/nfs/test/packages/RestBlockDriver modules
make[1]: Entering directory `/usr/src/linux-headers-3.2.0-61-generic'
  CC [M]  /nfs/test/packages/RestBlockDriver/dewb.o
/nfs/test/packages/RestBlockDriver/dewb.c: In function ‘dewb_device_detach_by_name’:
/nfs/test/packages/RestBlockDriver/dewb.c:777:8: error: implicit declaration of function ‘kbasename’ [-Werror=implicit-function-declaration]
/nfs/test/packages/RestBlockDriver/dewb.c:777:10: warning: initialization makes pointer from integer without a cast [enabled by default]
/nfs/test/packages/RestBlockDriver/dewb.c: In function ‘dewb_device_extend’:
/nfs/test/packages/RestBlockDriver/dewb.c:970:10: warning: initialization makes pointer from integer without a cast [enabled by default]
/nfs/test/packages/RestBlockDriver/dewb.c: In function ‘dewb_device_destroy’:
/nfs/test/packages/RestBlockDriver/dewb.c:1017:10: warning: initialization makes pointer from integer without a cast [enabled by default]
cc1: some warnings being treated as errors
make[2]: *** [/nfs/test/packages/RestBlockDriver/dewb.o] Error 1
make[1]: *** [_module_/nfs/test/packages/RestBlockDriver] Error 2
make[1]: Leaving directory`/usr/src/linux-headers-3.2.0-61-generic'
make: **\* [all] Error 2
root@app05:/nfs/test/packages/RestBlockDriver#
### So I hardcoded in dewb.c and dewb_sysfs.c as static inline

static inline const char *kbasename(const char *path) {
           const char *tail = strrchr(path, '/');
           return tail ? tail + 1 : path;
}

2) Then, got this: 

root@app05:/nfs/test/packages/RestBlockDriver# make
make -C /lib/modules/3.2.0-61-generic/build M=/nfs/test/packages/RestBlockDriver modules
make[1]: Entering directory `/usr/src/linux-headers-3.2.0-61-generic'
  CC [M]  /nfs/test/packages/RestBlockDriver/dewb_cdmi.o
/nfs/test/packages/RestBlockDriver/dewb_cdmi.c: In function ‘sock_xmit’:
/nfs/test/packages/RestBlockDriver/dewb_cdmi.c:238:48: error: ‘__GFP_MEMALLOC’ undeclared (first use in this function)
/nfs/test/packages/RestBlockDriver/dewb_cdmi.c:238:48: note: each undeclared identifier is reported only once for each function it appears in
/nfs/test/packages/RestBlockDriver/dewb_cdmi.c:280:2: error: implicit declaration of function ‘tsk_restore_flags’ [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
make[2]: *** [/nfs/test/packages/RestBlockDriver/dewb_cdmi.o] Error 1
make[1]: *** [_module_/nfs/test/packages/RestBlockDriver] Error 2
make[1]: Leaving directory`/usr/src/linux-headers-3.2.0-61-generic'
make: **\* [all] Error 2

<-- But there is not GFP_MEALLOC in linux/gfp.h

root@app05:/usr/src/linux-headers-3.2.0-61/include/linux# pwd
/usr/src/linux-headers-3.2.0-61/include/linux
root@app05:/usr/src/linux-headers-3.2.0-61/include/linux# find . | xargs grep __GFP_MEMALLOC
root@app05:/usr/src/linux-headers-3.2.0-61/include/linux# find . | xargs grep MEMALLOC
./sched.h:#define PF_MEMALLOC   0x00000800      /\* Allocating memory _/
./gfp.h:#define ___GFP_NOMEMALLOC       0x10000u
./gfp.h:#define __GFP_NOMEMALLOC ((__force gfp_t)___GFP_NOMEMALLOC) /_ Don't use emergency reserves */
./gfp.h:                         __GFP_NOMEMALLOC | __GFP_NORETRY | __GFP_NOWARN | \
./gfp.h:                        __GFP_NORETRY|__GFP_NOMEMALLOC)
root@app05:/usr/src/linux-headers-3.2.0-61/include/linux#

 26 #define ___GFP_MEMALLOC         0x2000u
 27 #define ___GFP_COMP             0x4000u
 28 #define ___GFP_ZERO             0x8000u
 29 #define ___GFP_NOMEMALLOC       0x10000u
### So I hardcoded #define ___GFP_MEMALLOC         0x2000u into dewb_cdmi.c

3) Then, I got this.

root@app05:/nfs/test/packages/RestBlockDriver# make
make -C /lib/modules/3.2.0-61-generic/build M=/nfs/test/packages/RestBlockDriver modules
make[1]: Entering directory `/usr/src/linux-headers-3.2.0-61-generic'
  CC [M]  /nfs/test/packages/RestBlockDriver/dewb_cdmi.o
/nfs/test/packages/RestBlockDriver/dewb_cdmi.c: In function ‘sock_xmit’:
/nfs/test/packages/RestBlockDriver/dewb_cdmi.c:283:2: error: implicit declaration of function ‘tsk_restore_flags’ [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
make[2]: *** [/nfs/test/packages/RestBlockDriver/dewb_cdmi.o] Error 1
make[1]: *** [_module_/nfs/test/packages/RestBlockDriver] Error 2
make[1]: Leaving directory`/usr/src/linux-headers-3.2.0-61-generic'
make: **\* [all] Error 2
root@app05:/nfs/test/packages/RestBlockDriver#
## So I hardcoded static inline into dewb_cdmi.c

static inline void tsk_restore_flags(struct task_struct *task,
                                     unsigned long orig_flags, unsigned long flags)
{
  task->flags &= ~flags;
  task->flags |= orig_flags & flags;
}

Then, I got the LKM. 

root@app05:/nfs/test/packages/RestBlockDriver# make
make -C /lib/modules/3.2.0-61-generic/build M=/nfs/test/packages/RestBlockDriver modules
make[1]: Entering directory `/usr/src/linux-headers-3.2.0-61-generic'
  CC [M]  /nfs/test/packages/RestBlockDriver/dewb.o
  CC [M]  /nfs/test/packages/RestBlockDriver/dewb_sysfs.o
  CC [M]  /nfs/test/packages/RestBlockDriver/dewb_cdmi.o
  CC [M]  /nfs/test/packages/RestBlockDriver/dewb_http.o
  CC [M]  /nfs/test/packages/RestBlockDriver/jsmn/jsmn.o
  LD [M]  /nfs/test/packages/RestBlockDriver/dewblock.o
  Building modules, stage 2.
make[2]: Warning: File`/nfs/test/packages/RestBlockDriver/dewblock.o' has modification time 0.025 s in the future
  MODPOST 1 modules
  CC      /nfs/test/packages/RestBlockDriver/dewblock.mod.o
  LD [M]  /nfs/test/packages/RestBlockDriver/dewblock.ko
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[1]: Leaving directory `/usr/src/linux-headers-3.2.0-61-generic'
root@app05:/nfs/test/packages/RestBlockDriver# ls
dewb.c       dewb_cdmi.o  dewb_http.c  dewblock.ko     dewblock.mod.o  dewb.o        dewb_sysfs.o  Makefile       Module.symvers  udev
dewb_cdmi.c  dewb.h       dewb_http.o  dewblock.mod.c  dewblock.o      dewb_sysfs.c  jsmn          modules.order  README.md
root@app05:/nfs/test/packages/RestBlockDriver#

root@app05:/nfs/test/packages/RestBlockDriver# lsmod | grep dewblock
dewblock            136511423  0
[1794043.319453] dewb: Installing dewblock module

Finally works!
